//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggerService.ReefAngelService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReefAngelParams", Namespace="http://schemas.datacontract.org/2004/07/ReefAngelWCFListener")]
    [System.SerializableAttribute()]
    public partial class ReefAngelParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ParamTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Temp1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Temp2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Temp3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PH {
            get {
                return this.PHField;
            }
            set {
                if ((object.ReferenceEquals(this.PHField, value) != true)) {
                    this.PHField = value;
                    this.RaisePropertyChanged("PH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ParamTime {
            get {
                return this.ParamTimeField;
            }
            set {
                if ((this.ParamTimeField.Equals(value) != true)) {
                    this.ParamTimeField = value;
                    this.RaisePropertyChanged("ParamTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Temp1 {
            get {
                return this.Temp1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Temp1Field, value) != true)) {
                    this.Temp1Field = value;
                    this.RaisePropertyChanged("Temp1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Temp2 {
            get {
                return this.Temp2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Temp2Field, value) != true)) {
                    this.Temp2Field = value;
                    this.RaisePropertyChanged("Temp2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Temp3 {
            get {
                return this.Temp3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Temp3Field, value) != true)) {
                    this.Temp3Field = value;
                    this.RaisePropertyChanged("Temp3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReefAngelRelayData", Namespace="http://schemas.datacontract.org/2004/07/ReefAngelWCFListener")]
    [System.SerializableAttribute()]
    public partial class ReefAngelRelayData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay1MaskOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay1MaskOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay1OnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay2MaskOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay2MaskOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay2OnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay3MaskOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay3MaskOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay3OnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay4MaskOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay4MaskOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay4OnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay5MaskOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay5MaskOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay5OnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay6MaskOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay6MaskOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay6OnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay7MaskOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay7MaskOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay7OnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay8MaskOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay8MaskOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Relay8OnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay1MaskOff {
            get {
                return this.Relay1MaskOffField;
            }
            set {
                if ((this.Relay1MaskOffField.Equals(value) != true)) {
                    this.Relay1MaskOffField = value;
                    this.RaisePropertyChanged("Relay1MaskOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay1MaskOn {
            get {
                return this.Relay1MaskOnField;
            }
            set {
                if ((this.Relay1MaskOnField.Equals(value) != true)) {
                    this.Relay1MaskOnField = value;
                    this.RaisePropertyChanged("Relay1MaskOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay1On {
            get {
                return this.Relay1OnField;
            }
            set {
                if ((this.Relay1OnField.Equals(value) != true)) {
                    this.Relay1OnField = value;
                    this.RaisePropertyChanged("Relay1On");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay2MaskOff {
            get {
                return this.Relay2MaskOffField;
            }
            set {
                if ((this.Relay2MaskOffField.Equals(value) != true)) {
                    this.Relay2MaskOffField = value;
                    this.RaisePropertyChanged("Relay2MaskOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay2MaskOn {
            get {
                return this.Relay2MaskOnField;
            }
            set {
                if ((this.Relay2MaskOnField.Equals(value) != true)) {
                    this.Relay2MaskOnField = value;
                    this.RaisePropertyChanged("Relay2MaskOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay2On {
            get {
                return this.Relay2OnField;
            }
            set {
                if ((this.Relay2OnField.Equals(value) != true)) {
                    this.Relay2OnField = value;
                    this.RaisePropertyChanged("Relay2On");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay3MaskOff {
            get {
                return this.Relay3MaskOffField;
            }
            set {
                if ((this.Relay3MaskOffField.Equals(value) != true)) {
                    this.Relay3MaskOffField = value;
                    this.RaisePropertyChanged("Relay3MaskOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay3MaskOn {
            get {
                return this.Relay3MaskOnField;
            }
            set {
                if ((this.Relay3MaskOnField.Equals(value) != true)) {
                    this.Relay3MaskOnField = value;
                    this.RaisePropertyChanged("Relay3MaskOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay3On {
            get {
                return this.Relay3OnField;
            }
            set {
                if ((this.Relay3OnField.Equals(value) != true)) {
                    this.Relay3OnField = value;
                    this.RaisePropertyChanged("Relay3On");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay4MaskOff {
            get {
                return this.Relay4MaskOffField;
            }
            set {
                if ((this.Relay4MaskOffField.Equals(value) != true)) {
                    this.Relay4MaskOffField = value;
                    this.RaisePropertyChanged("Relay4MaskOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay4MaskOn {
            get {
                return this.Relay4MaskOnField;
            }
            set {
                if ((this.Relay4MaskOnField.Equals(value) != true)) {
                    this.Relay4MaskOnField = value;
                    this.RaisePropertyChanged("Relay4MaskOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay4On {
            get {
                return this.Relay4OnField;
            }
            set {
                if ((this.Relay4OnField.Equals(value) != true)) {
                    this.Relay4OnField = value;
                    this.RaisePropertyChanged("Relay4On");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay5MaskOff {
            get {
                return this.Relay5MaskOffField;
            }
            set {
                if ((this.Relay5MaskOffField.Equals(value) != true)) {
                    this.Relay5MaskOffField = value;
                    this.RaisePropertyChanged("Relay5MaskOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay5MaskOn {
            get {
                return this.Relay5MaskOnField;
            }
            set {
                if ((this.Relay5MaskOnField.Equals(value) != true)) {
                    this.Relay5MaskOnField = value;
                    this.RaisePropertyChanged("Relay5MaskOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay5On {
            get {
                return this.Relay5OnField;
            }
            set {
                if ((this.Relay5OnField.Equals(value) != true)) {
                    this.Relay5OnField = value;
                    this.RaisePropertyChanged("Relay5On");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay6MaskOff {
            get {
                return this.Relay6MaskOffField;
            }
            set {
                if ((this.Relay6MaskOffField.Equals(value) != true)) {
                    this.Relay6MaskOffField = value;
                    this.RaisePropertyChanged("Relay6MaskOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay6MaskOn {
            get {
                return this.Relay6MaskOnField;
            }
            set {
                if ((this.Relay6MaskOnField.Equals(value) != true)) {
                    this.Relay6MaskOnField = value;
                    this.RaisePropertyChanged("Relay6MaskOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay6On {
            get {
                return this.Relay6OnField;
            }
            set {
                if ((this.Relay6OnField.Equals(value) != true)) {
                    this.Relay6OnField = value;
                    this.RaisePropertyChanged("Relay6On");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay7MaskOff {
            get {
                return this.Relay7MaskOffField;
            }
            set {
                if ((this.Relay7MaskOffField.Equals(value) != true)) {
                    this.Relay7MaskOffField = value;
                    this.RaisePropertyChanged("Relay7MaskOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay7MaskOn {
            get {
                return this.Relay7MaskOnField;
            }
            set {
                if ((this.Relay7MaskOnField.Equals(value) != true)) {
                    this.Relay7MaskOnField = value;
                    this.RaisePropertyChanged("Relay7MaskOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay7On {
            get {
                return this.Relay7OnField;
            }
            set {
                if ((this.Relay7OnField.Equals(value) != true)) {
                    this.Relay7OnField = value;
                    this.RaisePropertyChanged("Relay7On");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay8MaskOff {
            get {
                return this.Relay8MaskOffField;
            }
            set {
                if ((this.Relay8MaskOffField.Equals(value) != true)) {
                    this.Relay8MaskOffField = value;
                    this.RaisePropertyChanged("Relay8MaskOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay8MaskOn {
            get {
                return this.Relay8MaskOnField;
            }
            set {
                if ((this.Relay8MaskOnField.Equals(value) != true)) {
                    this.Relay8MaskOnField = value;
                    this.RaisePropertyChanged("Relay8MaskOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relay8On {
            get {
                return this.Relay8OnField;
            }
            set {
                if ((this.Relay8OnField.Equals(value) != true)) {
                    this.Relay8OnField = value;
                    this.RaisePropertyChanged("Relay8On");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReefAngelService.IReefAngelListener", CallbackContract=typeof(LoggerService.ReefAngelService.IReefAngelListenerCallback))]
    public interface IReefAngelListener {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReefAngelListener/Subscribe", ReplyAction="http://tempuri.org/IReefAngelListener/SubscribeResponse")]
        System.Guid Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IReefAngelListener/Unsubscribe")]
        void Unsubscribe(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IReefAngelListener/KeepConnection")]
        void KeepConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReefAngelListener/SendParams", ReplyAction="http://tempuri.org/IReefAngelListener/SendParamsResponse")]
        void SendParams(LoggerService.ReefAngelService.ReefAngelParams paras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReefAngelListener/SendRelayData", ReplyAction="http://tempuri.org/IReefAngelListener/SendRelayDataResponse")]
        void SendRelayData(LoggerService.ReefAngelService.ReefAngelRelayData relayData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReefAngelListenerCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReefAngelListener/HandleParams", ReplyAction="http://tempuri.org/IReefAngelListener/HandleParamsResponse")]
        void HandleParams(LoggerService.ReefAngelService.ReefAngelParams paras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReefAngelListener/HandleRelayData", ReplyAction="http://tempuri.org/IReefAngelListener/HandleRelayDataResponse")]
        void HandleRelayData(LoggerService.ReefAngelService.ReefAngelRelayData relayData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReefAngelListenerChannel : LoggerService.ReefAngelService.IReefAngelListener, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReefAngelListenerClient : System.ServiceModel.DuplexClientBase<LoggerService.ReefAngelService.IReefAngelListener>, LoggerService.ReefAngelService.IReefAngelListener {
        
        public ReefAngelListenerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ReefAngelListenerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ReefAngelListenerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ReefAngelListenerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ReefAngelListenerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public System.Guid Subscribe() {
            return base.Channel.Subscribe();
        }
        
        public void Unsubscribe(System.Guid clientId) {
            base.Channel.Unsubscribe(clientId);
        }
        
        public void KeepConnection() {
            base.Channel.KeepConnection();
        }
        
        public void SendParams(LoggerService.ReefAngelService.ReefAngelParams paras) {
            base.Channel.SendParams(paras);
        }
        
        public void SendRelayData(LoggerService.ReefAngelService.ReefAngelRelayData relayData) {
            base.Channel.SendRelayData(relayData);
        }
    }
}
